/* eslint-disable */
// @ts-nocheck
// biome-ignore lint: disable
// oxlint-disable
// ------
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399

export {}

/* prettier-ignore */
declare module 'vue' {
  export interface GlobalComponents {
    Button: typeof import('./components/Button.vue')['default']
    Input: typeof import('./components/Input.vue')['default']
    Modal: typeof import('./components/Modal.vue')['default']
    Select: typeof import('./components/Select.vue')['default']
  }
}
